/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,jsx}'],
    theme: {
        extend: {
            colors: {
                surface: '#f8f9fa',
                'surface-dim': '#d9dadb',
                'surface-bright': '#f8f9fa',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f3f4f5',
                'surface-container': '#edeeef',
                'surface-container-high': '#e7e8e9',
                'surface-container-highest': '#e1e3e4',
                background: '#f8f9fa',
                'on-background': '#191c1d',
                surfaceVariant: '#e1e3e4',
                'surface-variant': '#e1e3e4',
                'on-surface': '#191c1d',
                'on-surface-variant': '#3d4947',
                outline: '#6d7a77',
                'outline-variant': '#bcc9c6',
                'surface-tint': '#006a61',
                primary: '#00685f',
                'on-primary': '#ffffff',
                'primary-container': '#008378',
                'on-primary-container': '#f4fffc',
                'primary-fixed': '#89f5e7',
                'primary-fixed-dim': '#6bd8cb',
                'on-primary-fixed': '#00201d',
                'on-primary-fixed-variant': '#005049',
                'inverse-primary': '#6bd8cb',
                secondary: '#466557',
                'on-secondary': '#ffffff',
                'secondary-container': '#c8ead8',
                'on-secondary-container': '#4c6b5d',
                'secondary-fixed': '#c8ead8',
                'secondary-fixed-dim': '#adcebd',
                'on-secondary-fixed': '#022016',
                'on-secondary-fixed-variant': '#2f4d40',
                tertiary: '#755717',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#90702e',
                'on-tertiary-container': '#fffbff',
                'tertiary-fixed': '#ffdea5',
                'tertiary-fixed-dim': '#e9c176',
                'on-tertiary-fixed': '#261900',
                'on-tertiary-fixed-variant': '#5d4201',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'inverse-surface': '#2e3132',
                'inverse-on-surface': '#f0f1f2',
                'inverse-primary': '#6bd8cb',
                brand: {
                    50: '#ecfdf8',
                    100: '#d1faef',
                    200: '#a7f3dc',
                    300: '#6ee7c9',
                    400: '#34d1b0',
                    500: '#0d9488',
                    600: '#0b7f76',
                    700: '#0a6b64',
                    800: '#095650',
                    900: '#074541',
                },
                gold: {
                    50: '#fff9ec',
                    100: '#fff2c7',
                    200: '#ffe38b',
                    300: '#ffd45a',
                    400: '#f8be31',
                    500: '#d4a12c',
                    600: '#b98320',
                },
                sage: {
                    50: '#f4f8f2',
                    100: '#e3efe1',
                    200: '#c7dbc4',
                    300: '#a2bf9f',
                    400: '#7a9e77',
                    500: '#5f815b',
                },
            },
            fontFamily: {
                'display-lg': ['"Playfair Display"', 'serif'],
                'headline-lg': ['"Playfair Display"', 'serif'],
                'headline-lg-mobile': ['"Playfair Display"', 'serif'],
                'headline-md': ['"Playfair Display"', 'serif'],
                'headline-sm': ['"Playfair Display"', 'serif'],
                'body-lg': ['"DM Sans"', 'sans-serif'],
                'body-md': ['"DM Sans"', 'sans-serif'],
                'label-md': ['"DM Sans"', 'sans-serif'],
                'label-sm': ['"DM Sans"', 'sans-serif'],
                display: ['"Playfair Display"', 'serif'],
                body: ['"DM Sans"', 'sans-serif'],
            },
            fontSize: {
                'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
                'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
                'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
                'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
                'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '700' }],
            },
            borderRadius: {
                sm: '0.125rem',
                DEFAULT: '0.25rem',
                md: '0.375rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'container-max': '1280px',
                gutter: '24px',
                'margin-desktop': '64px',
                'margin-mobile': '20px',
                'stack-unit': '8px',
                airy: '120px',
            },
            boxShadow: {
                soft: '0 18px 40px rgba(15, 23, 42, 0.08)',
                lift: '0 28px 70px rgba(13, 148, 136, 0.14)',
            },
            backgroundImage: {
                'hero-gradient':
                    'radial-gradient(circle at top left, rgba(13, 148, 136, 0.18), transparent 38%), radial-gradient(circle at top right, rgba(212, 161, 44, 0.18), transparent 34%), linear-gradient(180deg, #ffffff 0%, #f7fbfa 100%)',
            },
        },
    },
    plugins: [],
};